TRAIN:
  ENABLE: True
  DATASET: Actiongenome
  BATCH_SIZE: 16
  EVAL_PERIOD: 3
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: False
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: "./ckpt/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: "caffe2"
  MULTI_LOSS: True
TEST:
  ENABLE: False
DATA:
  NUM_FRAMES: 32
  NUM_BOXES: 4
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.485, 0.456, 0.406]
  PATH_TO_DATA_DIR: '/mnt/data0/home/lxs/FSL_Datasets/action_genome'
  MULTI_LABEL: True
SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1]
  STEPS: [0, 35]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.001
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.0
SLOWFAST:
  ALPHA: 4
VIT:
  PATCH_SIZE: 16
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 3
  NUM_HEADS: 12
  MLP_RATIO: 2
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  USE_POS: none
  DROP: 0.5
  POS_DROPOUT: 0.5
  DROP_PATH: 0.0
  HEAD_DROPOUT: 0.5
  ATTN_DROPOUT: 0.0
  HEAD_ACT: gelu
REASON:
  VIS_DEPTHS: [2, 2]
  BOX_DEPTHS: [2, 2]
  SPE: grid
  BOX_PRETRAIN: ag_results/box/checkpoints/checkpoint_epoch_00020.pyth
MODEL:
  NUM_CLASSES: 157
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce_logit
  HEAD: reason_region
  USE_CLS: False
  HEAD_ACT: sigmoid
  
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: batchnorm
  CUSTOM_SYNC: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 123
OUTPUT_DIR: ./ag_results/reason_visbox
