TRAIN:
  ENABLE: True
  DATASET: Sthelse
  BATCH_SIZE: 32
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 60
  AUTO_RESUME: False
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: "results/reason_visbox_fewshot_base/checkpoints/checkpoint_epoch_00010.pyth"
  CHECKPOINT_TYPE: "pytorch"
  MULTI_LOSS: True
  MIXUP: False
  FS_FINETUNE: True
TEST:
  ENABLE: False
DATA:
  NUM_FRAMES: 32
  NUM_BOXES: 5
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.485, 0.456, 0.406]
  PATH_TO_DATA_DIR: '/mnt/data0/home/lxs/FSL_Datasets/sth-sth-v2'
  STHELSE_SPLIT: fewshot/finetune/5shot
SOLVER:
  BASE_LR: 0.01
  BOX_LR: 0.000005
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.1]
  STEPS: [0, 35, 45]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: sgd
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.0
  CUSTOM_OPTIM: False
SLOWFAST:
  ALPHA: 4
VIT:
  PATCH_SIZE: 16
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 3
  NUM_HEADS: 12
  MLP_RATIO: 2
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.2
  POS_DROPOUT: 0.2
  DROP_PATH: 0.0
  HEAD_DROPOUT: 0.5
  ATTN_DROPOUT: 0.0
  HEAD_ACT: gelu
  USE_POS: sine
  ATTACH_POS: add
  POS_EACH_LAYER: True
REASON:
  VIS_DEPTHS: [2, 2]
  BOX_DEPTHS: [2, 2]
  BOX_USE_CLS: False
MODEL:
  NUM_CLASSES: 86
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  HEAD: reason_region
  USE_CLS: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: batchnorm
  CUSTOM_SYNC: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 123
OUTPUT_DIR: ./results/reason_visbox_5_shot_sgd