TRAIN:
  ENABLE: True
  DATASET: Sthelse
  BATCH_SIZE: 16
  EVAL_PERIOD: 3
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: "results/sf_region/checkpoints/checkpoint_epoch_00015.pyth"
  CHECKPOINT_TYPE: "pytorch"
DATA:
  NUM_FRAMES: 32
  NUM_BOXES: 5
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.485, 0.456, 0.406]
  # neither /home/lxs or /home/lixunsong
  PATH_TO_DATA_DIR: '/mnt/data0/home/lixunsong/FSL_Datasets/sth-sth-v2'
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1]
  STEPS: [0, 2]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: sgd
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.0
SLOWFAST:
  ALPHA: 4
VIT:
  MLP_RATIO: 2
  PATCH_SIZE: 16
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 3
  NUM_HEADS: 12
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.5
  POS_DROPOUT: 0.5
  DROP_PATH: 0.0
  HEAD_DROPOUT: 0.5
  ATTN_DROPOUT: 0.0
  HEAD_ACT: gelu
REASON:
  BOX_PRETRAIN: 'results/box_bs16/checkpoints/checkpoint_epoch_00010.pyth'
  BOX_DEPTHS: [2, 2]
MODEL:
  NUM_CLASSES: 174
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  HEAD: region_fusion
  FINETUNE: True
  USE_CLS: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
BN:
  USE_PRECISE_STATS: False  # 如果要使用 bbox, 那么目前不能用 precise bn, 因为默认只会调用 model(input), 而不是 model(inputs, boxes)
  NUM_BATCHES_PRECISE: 200
  NUM_SYNC_DEVICES: 1
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 123
DEBUG: False
OUTPUT_DIR: sf_region_fusion
