TRAIN:
  ENABLE: True
  DATASET: Sthelse
  BATCH_SIZE: 32
  EVAL_PERIOD: 3
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: "./ckpt/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: "caffe2"
TEST:
  ENABLE: False
DATA:
  NUM_FRAMES: 32
  NUM_BOXES: 5
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.485, 0.456, 0.406]
  PATH_TO_DATA_DIR: '/mnt/data0/home/lixunsong/FSL_Datasets/sth-sth-v2'
SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1]
  STEPS: [0, 8]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.2
SLOWFAST:
  ALPHA: 4
MODEL:
  NUM_CLASSES: 174
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  HEAD: basic
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: batchnorm
  NUM_SYNC_DEVICES: 2
  CUSTOM_SYNC: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 123
OUTPUT_DIR: results/base_trunk
