TRAIN:
  ENABLE: True
  DATASET: Sthelse
  BATCH_SIZE: 16
  EVAL_PERIOD: 3
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: "./ckpt/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: "caffe2"
TEST:
  ENABLE: False
DATA:
  NUM_FRAMES: 32
  NUM_BOXES: 5
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.485, 0.456, 0.406]
  PATH_TO_DATA_DIR: '/mnt/data0/home/lxs/FSL_Datasets/sth-sth-v2'
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 10, 15]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: sgd
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.0
SLOWFAST:
  ALPHA: 4
VIT:
  PATCH_SIZE: 16
  CHANNELS: 3
  EMBED_DIM: 512
  DEPTH: 3
  NUM_HEADS: 8
  MLP_RATIO: 4
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.0
  POS_DROPOUT: 0.0
  DROP_PATH: 0.0
  HEAD_DROPOUT: 0.0
  HEAD_ACT: tanh
MODEL:
  NUM_CLASSES: 174
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  HEAD: traj_global
  HEAD_RESIDUAL: True
  USE_CLS: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 2
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 123
OUTPUT_DIR: ./results/traj_nocls
